name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  buildPushDeployToVps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t freego555/fastify-learn:latest .
          docker push freego555/fastify-learn:latest
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          CONFIG: ${{ vars.CONFIG }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs: CONFIG,FIREBASE_PROJECT_ID,FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY
          script: |
            cd fastify-learn-deploy
            echo "$CONFIG" > config.env
            dos2unix -n config.env .env
            set -a
            source .env
            set +a
            echo "PORT="$PORT"" > gh-actions-temp
            echo "USERS=$USERS" >> gh-actions-temp
            docker pull freego555/fastify-learn:latest
            docker stop fastify-learn
            docker rm fastify-learn
            docker run --privileged \
              -d \
              -e NODE_ENV="$NODE_ENV" \
              -e HOST="$HOST" \
              -e PORT="$PORT" \
              -e FIREBASE_PROJECT_ID="$FIREBASE_PROJECT_ID" \
              -e FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY="$FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY" \
              -e USERS="$USERS" \
              -p 3002:$PORT \
              --name fastify-learn \
              freego555/fastify-learn:latest
